version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employeedb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql

  prisma-studio:
    image: node:18
    container_name: prisma-studio
    working_dir: /app
    command: ["npx", "prisma", "studio"]
    env_file:
      - ./backend/.env
    ports:
      - "5555:5555"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  mysql_data:
